### ISSUE TITLE
Marketplace Availability

### ISSUE THREAD

**Issue by gte619n** [b-yp/logseq-image-editor#2]
Hello, is this available in the marketplace? I have been searching for this sort of plugin but have not been able to find it. Thank you!

**Comment by b-yp** [comment]
Please search for 'Image editor' in the plugin market
![image](https://github.com/b-yp/logseq-image-editor/assets/32813227/8e336bbb-3de8-45f8-a364-aa8dc1099827)

**Comment by gte619n** [comment]
Got it. Thank you.

**Comment by gte619n** [comment]
Got it. Thank you!
