### ISSUE TITLE
Shortcut Keys for Editor

### ISSUE THREAD

**Issue by gte619n** [b-yp/logseq-image-editor#4]
It would be great to be able to use 'esc' to close out of the editor.
It would be great to be able to use Ctrl + Enter to save the image and close the editor.

**Comment by b-yp** [comment]
Your suggestion is very good. It should be completed no later than this weekend. Thank you.

**Comment by b-yp** [comment]
Shortcut key added

**Comment by gte619n** [comment]
This works! Thank you!
